CREATE USER 'impacta'@'localhost' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON *.* TO 'impacta'@'localhost' WITH GRANT OPTION;

CREATE USER 'impacta'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON *.* TO 'impacta'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;